// 100 users with name, age, gender, email, and id
export const users = [
  {
    id: 1,
    name: 'John Smith',
    age: 32,
    gender: 'male',
    email: 'john.smith@example.com',
  },
  {
    id: 2,
    name: 'Jane Doe',
    age: 28,
    gender: 'female',
    email: 'jane.doe@example.com',
  },
  {
    id: 3,
    name: 'Michael Johnson',
    age: 45,
    gender: 'male',
    email: 'michael.johnson@example.com',
  },
  {
    id: 4,
    name: 'Emily Williams',
    age: 36,
    gender: 'female',
    email: 'emily.williams@example.com',
  },
  {
    id: 5,
    name: 'Robert Brown',
    age: 52,
    gender: 'male',
    email: 'robert.brown@example.com',
  },
  {
    id: 6,
    name: 'Sarah Davis',
    age: 24,
    gender: 'female',
    email: 'sarah.davis@example.com',
  },
  {
    id: 7,
    name: 'William Miller',
    age: 41,
    gender: 'male',
    email: 'william.miller@example.com',
  },
  {
    id: 8,
    name: 'Jessica Wilson',
    age: 29,
    gender: 'female',
    email: 'jessica.wilson@example.com',
  },
  {
    id: 9,
    name: 'David Moore',
    age: 38,
    gender: 'male',
    email: 'david.moore@example.com',
  },
  {
    id: 10,
    name: 'Jennifer Taylor',
    age: 33,
    gender: 'female',
    email: 'jennifer.taylor@example.com',
  },
  {
    id: 11,
    name: 'Richard Anderson',
    age: 47,
    gender: 'male',
    email: 'richard.anderson@example.com',
  },
  {
    id: 12,
    name: 'Lisa Thomas',
    age: 31,
    gender: 'female',
    email: 'lisa.thomas@example.com',
  },
  {
    id: 13,
    name: 'Charles Jackson',
    age: 56,
    gender: 'male',
    email: 'charles.jackson@example.com',
  },
  {
    id: 14,
    name: 'Nancy White',
    age: 27,
    gender: 'female',
    email: 'nancy.white@example.com',
  },
  {
    id: 15,
    name: 'Daniel Harris',
    age: 43,
    gender: 'male',
    email: 'daniel.harris@example.com',
  },
  {
    id: 16,
    name: 'Elizabeth Martin',
    age: 30,
    gender: 'female',
    email: 'elizabeth.martin@example.com',
  },
  {
    id: 17,
    name: 'Thomas Thompson',
    age: 39,
    gender: 'male',
    email: 'thomas.thompson@example.com',
  },
  {
    id: 18,
    name: 'Margaret Garcia',
    age: 26,
    gender: 'female',
    email: 'margaret.garcia@example.com',
  },
  {
    id: 19,
    name: 'Joseph Martinez',
    age: 50,
    gender: 'male',
    email: 'joseph.martinez@example.com',
  },
  {
    id: 20,
    name: 'Susan Robinson',
    age: 34,
    gender: 'female',
    email: 'susan.robinson@example.com',
  },
  {
    id: 21,
    name: 'Christopher Clark',
    age: 45,
    gender: 'male',
    email: 'christopher.clark@example.com',
  },
  {
    id: 22,
    name: 'Patricia Rodriguez',
    age: 29,
    gender: 'female',
    email: 'patricia.rodriguez@example.com',
  },
  {
    id: 23,
    name: 'Matthew Lewis',
    age: 36,
    gender: 'male',
    email: 'matthew.lewis@example.com',
  },
  {
    id: 24,
    name: 'Linda Lee',
    age: 31,
    gender: 'female',
    email: 'linda.lee@example.com',
  },
  {
    id: 25,
    name: 'Anthony Walker',
    age: 42,
    gender: 'male',
    email: 'anthony.walker@example.com',
  },
  {
    id: 26,
    name: 'Barbara Hall',
    age: 28,
    gender: 'female',
    email: 'barbara.hall@example.com',
  },
  {
    id: 27,
    name: 'Donald Allen',
    age: 53,
    gender: 'male',
    email: 'donald.allen@example.com',
  },
  {
    id: 28,
    name: 'Kimberly Young',
    age: 35,
    gender: 'female',
    email: 'kimberly.young@example.com',
  },
  {
    id: 29,
    name: 'Paul Hernandez',
    age: 40,
    gender: 'male',
    email: 'paul.hernandez@example.com',
  },
  {
    id: 30,
    name: 'Dorothy King',
    age: 32,
    gender: 'female',
    email: 'dorothy.king@example.com',
  },
  {
    id: 31,
    name: 'Mark Wright',
    age: 48,
    gender: 'male',
    email: 'mark.wright@example.com',
  },
  {
    id: 32,
    name: 'Sharon Scott',
    age: 27,
    gender: 'female',
    email: 'sharon.scott@example.com',
  },
  {
    id: 33,
    name: 'George Green',
    age: 51,
    gender: 'male',
    email: 'george.green@example.com',
  },
  {
    id: 34,
    name: 'Cynthia Adams',
    age: 33,
    gender: 'female',
    email: 'cynthia.adams@example.com',
  },
  {
    id: 35,
    name: 'Kenneth Baker',
    age: 44,
    gender: 'male',
    email: 'kenneth.baker@example.com',
  },
  {
    id: 36,
    name: 'Carol Nelson',
    age: 30,
    gender: 'female',
    email: 'carol.nelson@example.com',
  },
  {
    id: 37,
    name: 'Steven Hill',
    age: 37,
    gender: 'male',
    email: 'steven.hill@example.com',
  },
  {
    id: 38,
    name: 'Sandra Ramirez',
    age: 29,
    gender: 'female',
    email: 'sandra.ramirez@example.com',
  },
  {
    id: 39,
    name: 'Edward Campbell',
    age: 46,
    gender: 'male',
    email: 'edward.campbell@example.com',
  },
  {
    id: 40,
    name: 'Ruth Mitchell',
    age: 34,
    gender: 'female',
    email: 'ruth.mitchell@example.com',
  },
  {
    id: 41,
    name: 'Brian Roberts',
    age: 39,
    gender: 'male',
    email: 'brian.roberts@example.com',
  },
  {
    id: 42,
    name: 'Laura Carter',
    age: 31,
    gender: 'female',
    email: 'laura.carter@example.com',
  },
  {
    id: 43,
    name: 'Ronald Phillips',
    age: 54,
    gender: 'male',
    email: 'ronald.phillips@example.com',
  },
  {
    id: 44,
    name: 'Deborah Evans',
    age: 28,
    gender: 'female',
    email: 'deborah.evans@example.com',
  },
  {
    id: 45,
    name: 'Anthony Turner',
    age: 41,
    gender: 'male',
    email: 'anthony.turner@example.com',
  },
  {
    id: 46,
    name: 'Melissa Torres',
    age: 33,
    gender: 'female',
    email: 'melissa.torres@example.com',
  },
  {
    id: 47,
    name: 'Kevin Parker',
    age: 47,
    gender: 'male',
    email: 'kevin.parker@example.com',
  },
  {
    id: 48,
    name: 'Amanda Collins',
    age: 26,
    gender: 'female',
    email: 'amanda.collins@example.com',
  },
  {
    id: 49,
    name: 'Jason Edwards',
    age: 38,
    gender: 'male',
    email: 'jason.edwards@example.com',
  },
  {
    id: 50,
    name: 'Stephanie Stewart',
    age: 32,
    gender: 'female',
    email: 'stephanie.stewart@example.com',
  },
  {
    id: 51,
    name: 'Timothy Flores',
    age: 45,
    gender: 'male',
    email: 'timothy.flores@example.com',
  },
  {
    id: 52,
    name: 'Rebecca Morris',
    age: 29,
    gender: 'female',
    email: 'rebecca.morris@example.com',
  },
  {
    id: 53,
    name: 'Gary Nguyen',
    age: 50,
    gender: 'male',
    email: 'gary.nguyen@example.com',
  },
  {
    id: 54,
    name: 'Kathleen Murphy',
    age: 35,
    gender: 'female',
    email: 'kathleen.murphy@example.com',
  },
  {
    id: 55,
    name: 'Jose Rivera',
    age: 43,
    gender: 'male',
    email: 'jose.rivera@example.com',
  },
  {
    id: 56,
    name: 'Christine Cook',
    age: 31,
    gender: 'female',
    email: 'christine.cook@example.com',
  },
  {
    id: 57,
    name: 'Larry Morgan',
    age: 57,
    gender: 'male',
    email: 'larry.morgan@example.com',
  },
  {
    id: 58,
    name: 'Marie Bell',
    age: 28,
    gender: 'female',
    email: 'marie.bell@example.com',
  },
  {
    id: 59,
    name: 'Justin Bailey',
    age: 36,
    gender: 'male',
    email: 'justin.bailey@example.com',
  },
  {
    id: 60,
    name: 'Catherine Cooper',
    age: 34,
    gender: 'female',
    email: 'catherine.cooper@example.com',
  },
  {
    id: 61,
    name: 'Gerald Richardson',
    age: 49,
    gender: 'male',
    email: 'gerald.richardson@example.com',
  },
  {
    id: 62,
    name: 'Virginia Cox',
    age: 30,
    gender: 'female',
    email: 'virginia.cox@example.com',
  },
  {
    id: 63,
    name: 'Keith Howard',
    age: 42,
    gender: 'male',
    email: 'keith.howard@example.com',
  },
  {
    id: 64,
    name: 'Janice Ward',
    age: 27,
    gender: 'female',
    email: 'janice.ward@example.com',
  },
  {
    id: 65,
    name: 'Samuel Torres',
    age: 53,
    gender: 'male',
    email: 'samuel.torres@example.com',
  },
  {
    id: 66,
    name: 'Diane Peterson',
    age: 35,
    gender: 'female',
    email: 'diane.peterson@example.com',
  },
  {
    id: 67,
    name: 'Willie Gray',
    age: 44,
    gender: 'male',
    email: 'willie.gray@example.com',
  },
  {
    id: 68,
    name: 'Julie Ramirez',
    age: 32,
    gender: 'female',
    email: 'julie.ramirez@example.com',
  },
  {
    id: 69,
    name: 'Ralph James',
    age: 51,
    gender: 'male',
    email: 'ralph.james@example.com',
  },
  {
    id: 70,
    name: 'Joyce Watson',
    age: 29,
    gender: 'female',
    email: 'joyce.watson@example.com',
  },
  {
    id: 71,
    name: 'Henry Brooks',
    age: 39,
    gender: 'male',
    email: 'henry.brooks@example.com',
  },
  {
    id: 72,
    name: 'Heather Kelly',
    age: 33,
    gender: 'female',
    email: 'heather.kelly@example.com',
  },
  {
    id: 73,
    name: 'Johnny Sanders',
    age: 46,
    gender: 'male',
    email: 'johnny.sanders@example.com',
  },
  {
    id: 74,
    name: 'Frances Price',
    age: 31,
    gender: 'female',
    email: 'frances.price@example.com',
  },
  {
    id: 75,
    name: 'Wayne Bennett',
    age: 55,
    gender: 'male',
    email: 'wayne.bennett@example.com',
  },
  {
    id: 76,
    name: 'Evelyn Wood',
    age: 28,
    gender: 'female',
    email: 'evelyn.wood@example.com',
  },
  {
    id: 77,
    name: 'Roy Barnes',
    age: 41,
    gender: 'male',
    email: 'roy.barnes@example.com',
  },
  {
    id: 78,
    name: 'Cheryl Ross',
    age: 34,
    gender: 'female',
    email: 'cheryl.ross@example.com',
  },
  {
    id: 79,
    name: 'Eugene Henderson',
    age: 52,
    gender: 'male',
    email: 'eugene.henderson@example.com',
  },
  {
    id: 80,
    name: 'Rachel Coleman',
    age: 30,
    gender: 'female',
    email: 'rachel.coleman@example.com',
  },
  {
    id: 81,
    name: 'Bruce Jenkins',
    age: 47,
    gender: 'male',
    email: 'bruce.jenkins@example.com',
  },
  {
    id: 82,
    name: 'Marilyn Perry',
    age: 26,
    gender: 'female',
    email: 'marilyn.perry@example.com',
  },
  {
    id: 83,
    name: 'Louis Powell',
    age: 38,
    gender: 'male',
    email: 'louis.powell@example.com',
  },
  {
    id: 84,
    name: 'Tammy Russell',
    age: 32,
    gender: 'female',
    email: 'tammy.russell@example.com',
  },
  {
    id: 85,
    name: 'Craig Butler',
    age: 43,
    gender: 'male',
    email: 'craig.butler@example.com',
  },
  {
    id: 86,
    name: 'Lori Simmons',
    age: 29,
    gender: 'female',
    email: 'lori.simmons@example.com',
  },
  {
    id: 87,
    name: 'Ray Foster',
    age: 48,
    gender: 'male',
    email: 'ray.foster@example.com',
  },
  {
    id: 88,
    name: 'Anne Gonzales',
    age: 34,
    gender: 'female',
    email: 'anne.gonzales@example.com',
  },
  {
    id: 89,
    name: 'Earl Bryant',
    age: 56,
    gender: 'male',
    email: 'earl.bryant@example.com',
  },
  {
    id: 90,
    name: 'Wanda Alexander',
    age: 31,
    gender: 'female',
    email: 'wanda.alexander@example.com',
  },
  {
    id: 91,
    name: 'Fred Russell',
    age: 40,
    gender: 'male',
    email: 'fred.russell@example.com',
  },
  {
    id: 92,
    name: 'Theresa Griffin',
    age: 27,
    gender: 'female',
    email: 'theresa.griffin@example.com',
  },
  {
    id: 93,
    name: 'Howard West',
    age: 49,
    gender: 'male',
    email: 'howard.west@example.com',
  },
  {
    id: 94,
    name: 'Mildred Cole',
    age: 35,
    gender: 'female',
    email: 'mildred.cole@example.com',
  },
  {
    id: 95,
    name: 'Eugene Diaz',
    age: 54,
    gender: 'male',
    email: 'eugene.diaz@example.com',
  },
  {
    id: 96,
    name: 'Beverly Chen',
    age: 30,
    gender: 'female',
    email: 'beverly.chen@example.com',
  },
  {
    id: 97,
    name: 'Ernest Hunt',
    age: 45,
    gender: 'male',
    email: 'ernest.hunt@example.com',
  },
  {
    id: 98,
    name: 'Alice Freeman',
    age: 33,
    gender: 'female',
    email: 'alice.freeman@example.com',
  },
  {
    id: 99,
    name: 'Harry Wallace',
    age: 52,
    gender: 'male',
    email: 'harry.wallace@example.com',
  },
  {
    id: 100,
    name: 'Phyllis Long',
    age: 36,
    gender: 'female',
    email: 'phyllis.long@example.com',
  },
]

export default users
